### ISSUE TITLE
Asset highlight enhancements

### ISSUE THREAD

**Issue by WouterJansen** [realitymod/PRGallery#5]
Make it so if you hover over an asset on the map it highlights in the list and the other way around so you know which one is what.

**Comment by senshi-x** [comment]
Working on this.
Highlight will work like this:
Hover over icon on map -> the proper spawnercard in assetpanel lights up (bg-color change).
Hover over spawnercard -> all icons belonging to this spawnercard  light up (all other icons get 50% transparency, making the fitting icons stand out more).

Todo before PR:
- Icon highlights need to reset when no longer hovering over any spawnercard

Maybe-Todo:
- (Dbl)click on spawnercard should fit&zoom to the appropriate icon.
To discuss: What to do when multiple vehicles are aggregated in a card? Rotate through them (each click on it jumps to the next vehicle) or zoom and fit the map so all icons are visible.
